#%RAML 1.0 DataType
type: object
properties:
  msg:
    type: string
    required: true
    example: "success"    
  code:
    type: integer
    required: true
    example: 201
  success:
    type: boolean
    required: true
    example: true
  eventId:
    type: string
    required: true
    example: "sgft5dyor5avtre8t"                         
  data:
    type: object
    properties:
     memberId:
      type: string
      required: true
      example: "mem100" 
     status:
      type: string
      required: true
      example: "success"