#%RAML 1.0 Trait

headers:
  clientid:
    description: this header will contain client id
    type: string
    required: true
    example: "gkgjgg7785gg"
  clientsecret:
    description: this header will contain client secret
    type: string
    required: true
    example: "gugjgygu75r9tudho8y"