#%RAML 1.0 Trait

headers:
    X-lyt-transactionId:
      description: "this header will contain transaction ID"
      type: string
      required: true
      maxLength: 12
      minLength: 12
      example: "7777VHJG4544"