#%RAML 1.0 DataType
type: object
properties:
  msg:
    type: string
    required: true
    example: "success"    
  code:
    type: integer
    required: true
    example: 400
  success:
    type: boolean
    required: true
    example: true
  eventId:
    type: string
    required: true
    example: "sgft5dyor5avtre8t"                         
  error:
    type: object
    properties:
     type:
      type: string
      required: true
      example: "BAD_REQUEST" 
     title:
      type: string
      required: true
      example: "Invalid Request"
     details:
      type: string
      required: true
      example: "the input contains invalid data amount shuld be integer"