#%RAML 1.0 ResourceType

traits:
  clientid: /trait/clientidsecrettrait.raml
  business: /trait/business-trait.raml
  transactionid: /trait/transactionid-trait.raml
  Authorization: /trait/autharizationJWT.raml

types:
  errorResponce: /DataType/errorresponce-dataType.raml
  